# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe6284e44b3c3c8bb6f1149ff1eb1ad4ac37ca5dba32bb1a9734ab85c278904d937d110bd3ade4edd7e39652066aacfddab845d74549c42c1742f155d2af6c7

test:
  secret_key_base: 23d4952e55776291a636089a7376bca4ad60e1e1750f12de6fb77de6d8a142b84283970e085c765f7b54c31e405b950cfac4a77129c490ff04053abe0495141c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
